name: Pipeline de Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Usar Ubuntu mais recente para rodar o CI

    steps:
      # Checkout do código
      - name: Checkout do Código
        uses: actions/checkout@v3

      # Configuração do Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Versão do Python

      # Instalação de dependências
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala as dependências listadas no requirements.txt

      # Rodar os testes
      - name: Executar Testes
        run: |
          python -m unittest discover -s tests -p "*.py"  # Descobre e executa os testes no diretório "tests"

      # Gerar relatório de cobertura
      - name: Cobertura de Testes
        run: |
          pip install coverage  # Instala o pacote de cobertura
          coverage run -m unittest discover -s tests -p "*.py"  # Executa os testes com cobertura
          coverage report  # Exibe o relatório de cobertura no console

      # Upload do relatório de cobertura
      - name: Enviar Relatório de Cobertura
        if: always()  # Garante que o relatório de cobertura seja enviado mesmo se os testes falharem
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report  # Nome do arquivo do artefato
          path: .coverage  # Caminho para o arquivo de cobertura gerado
